### ISSUE TITLE
Syntax colour?

### ISSUE THREAD

**Issue by VaclavElias** [DamianEdwards/TagHelperStarterWeb#2]
I think this **TagHelper** is really cool thing but to make it easier to differentiate what is HTML and what is not would it be better to highlight somehow what is not HTML?

`<a controller="Home" action="Index" class="navbar-brand">Application name</a>`

`<form controller="Account" action="Login" route-returnurl="@ViewBag.ReturnUrl" method="post" class="form-horizontal" role="form">`

For example these:
`controller="Home" action="Index"`
`controller="Account" action="Login" route-returnurl="@ViewBag.ReturnUrl"`

could be with a different opacity (like new using... or something) so without even reading your new HTML you could spot in seconds which HTML tags contains server code. Also, if non-coder is working with HTML then he could get instructions to touch only HTML otherwise he might get slap his fingers if he modifies server code.

Don't ask me how to do it :)

Thanks :)

**Comment by DamianEdwards** [comment]
We fully intend to have extensive tooling support for Tag Helpers in Visual Studio 2015 when it RTMs. We won't put Tag Helpers into the project templates until this happens as it's not a very pleasant experience right now as you've pointed out :smile: 

Once we do get support, you'll enjoy:
- Statement completion for Tag Helper directives, e.g. `@addTagHelper`
- Statement completion for Tag Helper elements and attributes including descriptions
- Classification of Tag Helper elements (so you can make them a different color, etc.)
- Full IntelliSense inside Tag Helper attribute values, which are actually C# (as if you typed `@`)

Rest assured, as soon as it's checked in and I can install it, I'll be tweeting out a screenshot for all to see :smile:

**Comment by VaclavElias** [comment]
Sounds good! Thanks :)
