### ISSUE TITLE
IServiceManifest not registered

### ISSUE THREAD

**Issue by Antaris** [DamianEdwards/TagHelperStarterWeb#3]
Hi Damien,

I've cloned and tried to run this sample project, I'm running KRE 1.0.0-beta1 and have performed an appropriate kpm command to download the packages. Whenever I try to run (`k web`), I'm getting the following exception:

```
No service for type 'Microsoft.Framework.DependencyInjection.ServiceLookup.IServiceManifest' has been registered.
```

On checking a similar issue [here](https://github.com/aspnet/Home/issues/218), its suggested to perform a `kvm upgrade` to install the latest KRE. My install is telling me it has the latest KRE and this problem still persists.

Any help would be appreciated.

Environment: Windows 8.1

**Comment by aclave1** [comment]
I have this same issue on ubuntu 14.10

**Comment by DamianEdwards** [comment]
The sample is now up to date for beta3/ctp6. Let me know if you're still having issues.
