### ISSUE TITLE
What will be in the new default templates in Visual Studio 2015?

### ISSUE THREAD

**Issue by johnciliberti** [DamianEdwards/TagHelperStarterWeb#4]
Thanks for putting this together. It is very helpful for understanding how the tag helpers will work.
Any thoughts on what the final templates will look like in Visual Studio 2015?

In my opinion these templates and the scaffolding templates should be added to the main MVC github project so that they can be pier reviewed and improved with the input of the community.  It would also be nice to allow developers to pick which version of the templates they want to use as part of the new project experience.

**Comment by DamianEdwards** [comment]
We're working through those things now. Until we get support for Tag Helpers in Visual Studio (in the Razor editor) we won't add them to the project templates.

We're doing some work on the One ASP.NET dialog in the next release and also looking at how we can open up the templates to the community. Keep an eye on https://github.com/aspnet
